all:
  stylesheets: [/opCommunityTopicPlugin/css/communityTopic]

smtListCommunitySuccess:
  layout: smtLayoutSns

smtShowSuccess:
  layout: smtLayoutGroup

smtMemberListSuccess:
  layout: smtLayoutSns
